"""remove size of products

Revision ID: 6a449d54a2c1
Revises: 426e8fb1667a
Create Date: 2022-05-19 15:05:45.442926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a449d54a2c1'
down_revision = '426e8fb1667a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
